### ISSUE TITLE
Have you considered using DeepL's free windows integration?

### ISSUE THREAD

**Issue by Lhun** [VRCWizard/TTS-Voice-Wizard#2]
![image](https://user-images.githubusercontent.com/23122906/176929955-8bd112f1-e39d-4eb8-9226-d85f0f9cc952.png)
So DeepL supports capturing from applications, translating directly in applications, and piping text back and fourth, it also supports screen capture and ocr. 

As someone who uses it to communicate with a massive japanese team on the daily, it is by far the best and most accurate translation. And, it's completely free for the kind of use this application would be spitting out. 
It's paid options are for team translations documents and cat tools, all of which you don't need. 

I'm planning on using your tool to give myself jp closed captions in game (i'm less interested in the TTS portion) 
The azure requirement is a huge turn off for many, and to be honest it's translations aren't even all that good in comparison, especially for Japanese. 
This would create a completely free option for users that works with what is considered the best tool to work with japanese users.

**Comment by VRCWizard** [comment]
@Lhun This is a fantastic suggestion since azure "text translation" isn't free which is why you can not translate TTS in the main app. I have begun testing the API on the lite version of the app https://github.com/VRCWizard/TTS-Voice-Wizard-Lite/releases/tag/v0.1.1 which you can also test here (keep in mind the lite version is missing many features added in the main app such as setting saving for example). I plan to include this in the main app in a future update.

Side note: Kill Frenzy Avatar Text seems to be missing many Japanese symbols I am not sure if these symbols can be converted into other symbols that are included but as of right now any symbols not in KAT will appear as "?" in game. For example the highlighted symbols in this picture ("声","出","読") will appear as "?" in VRChat 
![image](https://user-images.githubusercontent.com/101527472/176961764-2e542ed0-fc9b-4d66-9740-7126ddfa6bd8.png)

If you have any insight into the issue let me know, Here are the symbols supported by KAT
![image](https://user-images.githubusercontent.com/101527472/176961967-ba2500a9-809b-4267-b2b5-78056a0bd5e3.png)

**Comment by Lhun** [comment]
Actually, I commented there first because I recognized this issue as well. I tested the tts with a native speaker using the azure mode and it ... wasn't well received. 
I made a comment on that particular issue with KFAT as well, s-silent is also engaged on this it seems.

https://github.com/killfrenzy96/KillFrenzyAvatarText/issues/6
